from employee import Employee
from person import Person
from office import Office
from car import Car
if __name__ == '__main__':
    c1 = Car('Fiat 128', 100, 100)
    c2 = Car('BMW', 300, 400)
    c3 = Car('Kia', 400, 300)
    e1 = Employee('Mostafa', 10000, 'Lazy', 75, 1, c1, 'mostafa@gmail.com', 6000, 100)
    e2 = Employee('Mohamed', 30000, 'Happy', 75, 2, c2, 'mohamed@gmail.com', 5000, 300)
    e3 = Employee('Hani', 30000, 'Happy', 75, 3, c2, 'daaa_haniiiii@gmail.com', 5000, 200)
    print(e1)
    print("-----------------------------------------------------------------------------------------------")
    print('Mostafa\'s money before buying any item: ', e1.money)
    e1.buy(4)
    print('Mostafa\'s money after buying 4 items: ', e1.money)
    print("-----------------------------------------------------------------------------------------------")
    e1.eat(3)
    print("Mostafa's health if he takes 3 meals everyday: ", e1.healthRate)
    e1.eat(2)
    print("Mostafa's health if he takes 2 meals everyday: ", e1.healthRate)
    e1.eat(1)
    print("Mostafa's health if the takes 1 meal everyday: ", e1.healthRate)
    print("-----------------------------------------------------------------------------------------------")
    e1.sleep(10)
    print("Mostafa's mood if he sleeps for more than 7 hours: ", e1.mood)
    e1.sleep(7)
    print("Mostafa's mood if he sleeps for 7 hours: ", e1.mood)
    e1.sleep(4)
    print("Mostafa's mood if he sleeps for less than 7 hours: ", e1.mood)
    print("-----------------------------------------------------------------------------------------------")
    print("When Mostafa Start driving his car to his work: ")
    e1.drive(100)
    print("-----------------------------------------------------------------------------------------------")
    e1.work(8)
    print('Mostafa\'s mood after working for 8 hours: ', e1.mood)
    e1.work(10)
    print('Mostafa\'s mood after working for more than 8 hours: ', e1.mood)
    e1.work(6)
    print('Mostafa\'s mood after working for less than 8 hours: ', e1.mood)
    print("-----------------------------------------------------------------------------------------------")
    print("Fuel Rate before refueling Mostafa's car: ", e1.car.fuelRate)
    e1.refuel(100)
    print("Fuel Rate after refueling Mostafa's car: ", e1.car.fuelRate)
    print("-----------------------------------------------------------------------------------------------")
    print('When Mostafa send email to Noha')
    e1.send_mail('noha@gmail.com', 'congratulating about getting master degree', 'Hi, eng/Noha\nI\'m writing to you to congratulate you about master degree\nhope you best wishes', 'Noha Shehab')
    print("Mostafa's massage to Noha:")
    f = open('Noha Shehab.txt')
    f.close()
    print(f.read())
    print("-----------------------------------------------------------------------------------------------")
    office1 = Office('office1', [e1, e2, e3])
    print(office1)
    print("-----------------------------------------------------------------------------------------------")
    print("Number of Employee in all offices before Firing any Employee: ", Office.employeesNum)
    office1.fire(2)
    print("Number of Employee in all offices after Firing e2 form office1: ", Office.employeesNum)
    print("-----------------------------------------------------------------------------------------------")
    print("Number of Employee in all offices before hiring any Employee: ", Office.employeesNum)
    office1.hire(e2)
    print("Number of Employee in all offices after hiring e2 for office1 again: ", Office.employeesNum)
    print("-----------------------------------------------------------------------------------------------")
    print('Checking if Mostafa who drive from home at 100 Km/h his work at office1 for which target time to arrive 9:00 is late or not:')
    print('Let that he moves from at 8:30 : ')
    print("Mostafa's salary before deduction: ", office1.get_employee(1).salary)
    office1.check_lateness(1, 8.5)
    print("Mostafa's salary after deduction: ", office1.get_employee(1).salary, '\n')

    print('Let That Mostafa moved from his home to work at 8:00 : ')
    print("Mostafa's salary before reward: ", office1.get_employee(1).salary)
    office1.check_lateness(1, 8)
    print("Mostafa's salary after reward: ", office1.get_employee(1).salary)
    print("-----------------------------------------------------------------------------------------------")
    print('List of Employees at office1: ', office1.get_all_employees())
    print("-----------------------------------------------------------------------------------------------")
    print('The data of the Employee whose Id is 3 and works at office1:\n' + str(office1.get_employee(3)))


